// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("CellCounter")>]
[<assembly: AssemblyProductAttribute("CellCounter")>]
[<assembly: AssemblyDescriptionAttribute("An application to automatically count cells using wavelet transformation")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "CellCounter"
    let [<Literal>] AssemblyProduct = "CellCounter"
    let [<Literal>] AssemblyDescription = "An application to automatically count cells using wavelet transformation"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
